package com.spk.application.form.Subcriteria;

import com.spk.application.form.criteria.*;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.fonts.roboto.FlatRobotoFont;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import com.spk.connection.Connections;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JProgressBar;
import javax.swing.UIManager;

/**
 *
 * @author Ridho Multazam
 */
public class addSubCriteria extends javax.swing.JFrame {

    /**
     * Creates new form Test
     */
    
    private String kodeKriteria;
        
    public addSubCriteria(String kodeKriteria) {
        initComponents();
        this.kodeKriteria = kodeKriteria;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crazyPanel1 = new raven.crazypanel.CrazyPanel();
        Title = new javax.swing.JLabel();
        codeSubCriteria = new javax.swing.JLabel();
        txcodeSubCriteria = new javax.swing.JTextField();
        nameSubCriteria = new javax.swing.JLabel();
        txnameSubCriteria = new javax.swing.JTextField();
        nilaiSubCriteria = new javax.swing.JLabel();
        txnilaiSubCriteria = new javax.swing.JTextField();
        btSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        crazyPanel1.setFlatLafStyleComponent(new raven.crazypanel.FlatLafStyleComponent(
            "[light]border:0,0,0,0,shade(@background,5%),,20;[dark]border:0,0,0,0,tint(@background,5%),,20;[light]background:shade(@background,2%);[dark]background:tint(@background,2%)",
            new String[]{
                "font:bold +10",
                "",
                "showClearButton:true",
                "",
                "showClearButton:true",
                "",
                "showClearButton:true",
                ""
            }
        ));
        crazyPanel1.setMigLayoutConstraints(new raven.crazypanel.MigLayoutConstraints(
            "wrap 2,fillx,insets 25",
            "[grow 0,trail]15[fill]",
            "",
            new String[]{
                "wrap,al lead",
                "",
                "",
                "",
                "",
                "",
                "",
                "span 2,al trail"
            }
        ));

        Title.setText("Tambah Sub Kriteria");
        crazyPanel1.add(Title);

        codeSubCriteria.setText("Kode Sub Kriteria");
        crazyPanel1.add(codeSubCriteria);
        crazyPanel1.add(txcodeSubCriteria);

        nameSubCriteria.setText("Nama Sub Kriteria");
        crazyPanel1.add(nameSubCriteria);
        crazyPanel1.add(txnameSubCriteria);

        nilaiSubCriteria.setText("Nilai Sub Kriteria");
        crazyPanel1.add(nilaiSubCriteria);
        crazyPanel1.add(txnilaiSubCriteria);

        btSave.setText("Simpan");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });
        crazyPanel1.add(btSave);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(crazyPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(crazyPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
      String namaSub = txnameSubCriteria.getText().trim();
        String nilaiSub = txnilaiSubCriteria.getText().trim();
        
        if (namaSub.isEmpty() || nilaiSub.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Semua field harus diisi!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return; // Stop the execution if validation fails
        }
        
        // Save sub-criteria to the database
        saveSubCriteria(kodeKriteria, txcodeSubCriteria.getText(), namaSub, Double.parseDouble(nilaiSub));
    }//GEN-LAST:event_btSaveActionPerformed

    
    private void saveSubCriteria(String kodeKriteria, String kodeSub, String namaSub, double subNilai) {
        try {
            Connection conn = Connections.getConnection();
            String sql = "INSERT INTO sub_criteria (kode_kriteria, kode_sub, nama_sub, sub_nilai) VALUES (?, ?, ?, ?)";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, kodeKriteria);
            stmt.setString(2, kodeSub);
            stmt.setString(3, namaSub);
            stmt.setDouble(4, subNilai);
            stmt.executeUpdate();

            stmt.close();
            Connections.closeConnection(conn);
            javax.swing.JOptionPane.showMessageDialog(this, "Sub Kriteria berhasil disimpan!");
            this.dispose(); // Close the dialog after saving
        } catch (SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error while saving Sub Kriteria: " + e.getMessage());
        }
    }
    
    public static void main(String args[]) {
        FlatRobotoFont.install();
        FlatLaf.registerCustomDefaultsSource("crazypanel");
        UIManager.put("defaultFont", new Font(FlatRobotoFont.FAMILY, Font.PLAIN, 13));
        FlatMacLightLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
            }
        });
    }       
            

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JButton btSave;
    private javax.swing.JLabel codeSubCriteria;
    private raven.crazypanel.CrazyPanel crazyPanel1;
    private javax.swing.JLabel nameSubCriteria;
    private javax.swing.JLabel nilaiSubCriteria;
    private javax.swing.JTextField txcodeSubCriteria;
    private javax.swing.JTextField txnameSubCriteria;
    private javax.swing.JTextField txnilaiSubCriteria;
    // End of variables declaration//GEN-END:variables
}
