package com.spk.application.form.Subcriteria;

import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.fonts.roboto.FlatRobotoFont;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import com.spk.connection.Connections;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JProgressBar;
import javax.swing.UIManager;

/**
 *
 * @author Ridho Multazam
 */
public class changeSubCriteria extends javax.swing.JFrame {

    /**
     * Creates new form Test
     */
    public changeSubCriteria(String kodeSub, String namaSub, double nilaiSub) {
        initComponents();
        new JProgressBar().setIndeterminate(true);
        
        // Set the text fields with the provided values
        txcodeSubCriteria.setText(kodeSub);
        txnameSubCriteria.setText(namaSub);
        txnilaiSubCriteria.setText(String.valueOf(nilaiSub));   
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crazyPanel1 = new raven.crazypanel.CrazyPanel();
        Title = new javax.swing.JLabel();
        codeSubCriteria = new javax.swing.JLabel();
        txcodeSubCriteria = new javax.swing.JTextField();
        nameSubCriteria = new javax.swing.JLabel();
        txnameSubCriteria = new javax.swing.JTextField();
        nilaiSubCriteria = new javax.swing.JLabel();
        txnilaiSubCriteria = new javax.swing.JTextField();
        btSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        crazyPanel1.setFlatLafStyleComponent(new raven.crazypanel.FlatLafStyleComponent(
            "[light]border:0,0,0,0,shade(@background,5%),,20;[dark]border:0,0,0,0,tint(@background,5%),,20;[light]background:shade(@background,2%);[dark]background:tint(@background,2%)",
            new String[]{
                "font:bold +10",
                "",
                "showClearButton:true",
                "",
                "showClearButton:true",
                "",
                "showClearButton:true",
                ""
            }
        ));
        crazyPanel1.setMigLayoutConstraints(new raven.crazypanel.MigLayoutConstraints(
            "wrap 2,fillx,insets 25",
            "[grow 0,trail]15[fill]",
            "",
            new String[]{
                "wrap,al lead",
                "",
                "",
                "",
                "",
                "",
                "",
                "span 2,al trail"
            }
        ));

        Title.setText("Ubah Sub Kriteria");
        crazyPanel1.add(Title);

        codeSubCriteria.setText("Kode Sub Kriteria");
        crazyPanel1.add(codeSubCriteria);
        crazyPanel1.add(txcodeSubCriteria);

        nameSubCriteria.setText("Nama Sub Kriteria");
        crazyPanel1.add(nameSubCriteria);
        crazyPanel1.add(txnameSubCriteria);

        nilaiSubCriteria.setText("Nilai Sub Kriteria");
        crazyPanel1.add(nilaiSubCriteria);
        crazyPanel1.add(txnilaiSubCriteria);

        btSave.setText("Simpan");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });
        crazyPanel1.add(btSave);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(crazyPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(crazyPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        // Get values from JTextField
        String kode = txcodeSubCriteria.getText().trim();
        String nama = txnameSubCriteria.getText().trim();
        String nilaiStr = txnilaiSubCriteria.getText().trim();

        // Validation for Sub Kriteria Code
        if (kode.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Kode Sub Kriteria tidak boleh kosong!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            txcodeSubCriteria.requestFocus();
            return;
        }

        // Validation for Sub Kriteria Name
        if (nama.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Nama Sub Kriteria tidak boleh kosong!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            txnameSubCriteria.requestFocus();
            return;
        }

        // Validation for Sub Kriteria Value
        double nilai;
        try {
            nilai = Double.parseDouble(nilaiStr);
            if (nilai < 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Nilai Sub Kriteria tidak boleh negatif!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
                txnilaiSubCriteria.requestFocus();
                return;
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Nilai Sub Kriteria harus berupa angka valid!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            txnilaiSubCriteria.requestFocus();
            return;
        }

        // If all validations pass, proceed to save the updated data
        updateSubCriteria(kode, nama, nilai);
    }//GEN-LAST:event_btSaveActionPerformed
    
    // Method to update sub-criteria in the database
    private void updateSubCriteria(String kode, String nama, double nilai) {
        try {
            // Logic to update the sub-criteria in the database
            Connection conn = Connections.getConnection();
            String sql = "UPDATE sub_criteria SET nama_sub = ?, sub_nilai = ? WHERE kode_sub = ?";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, nama);
            stmt.setDouble(2, nilai);
            stmt.setString(3, kode);
            stmt.executeUpdate();

            stmt.close();
            Connections.closeConnection(conn);

            javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!", "Informasi", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            // Optionally reset fields after saving
            txcodeSubCriteria.setText("");
            txnameSubCriteria.setText("");
            txnilaiSubCriteria.setText("");
        } catch (SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error saat memperbarui data: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    public static void main(String args[]) {
        FlatRobotoFont.install();
        FlatLaf.registerCustomDefaultsSource("crazypanel");
        UIManager.put("defaultFont", new Font(FlatRobotoFont.FAMILY, Font.PLAIN, 13));
        FlatMacLightLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
            }
        });
    }       
            

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JButton btSave;
    private javax.swing.JLabel codeSubCriteria;
    private raven.crazypanel.CrazyPanel crazyPanel1;
    private javax.swing.JLabel nameSubCriteria;
    private javax.swing.JLabel nilaiSubCriteria;
    private javax.swing.JTextField txcodeSubCriteria;
    private javax.swing.JTextField txnameSubCriteria;
    private javax.swing.JTextField txnilaiSubCriteria;
    // End of variables declaration//GEN-END:variables
}
