package com.spk.application.form.alternative;

import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.fonts.roboto.FlatRobotoFont;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import com.spk.connection.Connections;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.UIManager;

/**
 *
 * @author Ridho Multazam
 */
public class addAlternative extends javax.swing.JFrame {

    /**
     * Creates new form Test
     */
    public addAlternative() {
        initComponents();
        new JProgressBar().setIndeterminate(true);
    }
    
    private String generateNextKodeAlternatif(Connection conn) {
        try {
            String query = "SELECT kode_alternatif FROM alternatif ORDER BY kode_alternatif ASC";
            PreparedStatement ps = conn.prepareStatement(query);
            ResultSet rs = ps.executeQuery();

            int nextNumber = 1;
            while (rs.next()) {
                String kode = rs.getString("kode_alternatif").substring(1);
                int num = Integer.parseInt(kode);

                if (num == nextNumber) {
                    nextNumber++;
                } else {
                    break;
                }
            }

            return "A" + nextNumber;

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error generating kode_alternatif: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crazyPanel1 = new raven.crazypanel.CrazyPanel();
        Title = new javax.swing.JLabel();
        nameAlternative = new javax.swing.JLabel();
        txnameAlternative = new javax.swing.JTextField();
        btSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        crazyPanel1.setFlatLafStyleComponent(new raven.crazypanel.FlatLafStyleComponent(
            "[light]border:0,0,0,0,shade(@background,5%),,20;[dark]border:0,0,0,0,tint(@background,5%),,20;[light]background:shade(@background,2%);[dark]background:tint(@background,2%)",
            new String[]{
                "font:bold +10",
                "",
                "showClearButton:true",
                ""
            }
        ));
        crazyPanel1.setMigLayoutConstraints(new raven.crazypanel.MigLayoutConstraints(
            "wrap 2,fillx,insets 25",
            "[grow 0,trail]15[fill]",
            "",
            new String[]{
                "wrap,al lead",
                "",
                "",
                "span 2,al trail"
            }
        ));

        Title.setText("Tambah Alternatif");
        crazyPanel1.add(Title);

        nameAlternative.setText("Nama Alternatif");
        crazyPanel1.add(nameAlternative);
        crazyPanel1.add(txnameAlternative);

        btSave.setText("Simpan");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });
        crazyPanel1.add(btSave);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(crazyPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(crazyPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
         String namaAlternatif = txnameAlternative.getText().trim();

        if (namaAlternatif.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama alternatif tidak boleh kosong.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try (
            Connection conn = Connections.getConnection()
        ) {
            String nextKodeAlternatif = generateNextKodeAlternatif(conn);
            if (nextKodeAlternatif == null) {
                JOptionPane.showMessageDialog(this, "Gagal menghasilkan kode alternatif baru.", "Database Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            String insertQuery = "INSERT INTO alternatif (kode_alternatif, nama_alternatif) VALUES (?, ?)";
            try (PreparedStatement psInsert = conn.prepareStatement(insertQuery)) {
                psInsert.setString(1, nextKodeAlternatif);
                psInsert.setString(2, namaAlternatif);

                psInsert.executeUpdate();
            }

            JOptionPane.showMessageDialog(this, "Alternatif berhasil disimpan.", "Success", JOptionPane.INFORMATION_MESSAGE);

            txnameAlternative.setText("");

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btSaveActionPerformed

    public static void main(String args[]) {
        FlatRobotoFont.install();
        FlatLaf.registerCustomDefaultsSource("crazypanel");
        UIManager.put("defaultFont", new Font(FlatRobotoFont.FAMILY, Font.PLAIN, 13));
        FlatMacLightLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
            }
        });
    }       
            

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JButton btSave;
    private raven.crazypanel.CrazyPanel crazyPanel1;
    private javax.swing.JLabel nameAlternative;
    private javax.swing.JTextField txnameAlternative;
    // End of variables declaration//GEN-END:variables
}
