package com.spk.application.form.alternative;

import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.fonts.roboto.FlatRobotoFont;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import com.spk.connection.Connections;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.UIManager;

/**
 *
 * @author Ridho Multazam
 */
public class changeAlternative extends javax.swing.JFrame {
    private String kodeAlternatif;
    
    /**
     * Creates new form Test
     */
    public changeAlternative(String kodeAlternatif) {
        this.kodeAlternatif = kodeAlternatif;
        initComponents();
        loadAlternativeData();
    }
    
    private void loadAlternativeData() {
        try (
            Connection conn = Connections.getConnection()
        ) {
            String query = "SELECT nama_alternatif FROM alternatif WHERE kode_alternatif = ?";
            try (PreparedStatement ps = conn.prepareStatement(query)) {
                ps.setString(1, kodeAlternatif);
                try (ResultSet rs = ps.executeQuery()) {
                    if (rs.next()) {
                        String namaAlternatif = rs.getString("nama_alternatif");
                        txnameAlternative.setText(namaAlternatif);
                    }
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crazyPanel1 = new raven.crazypanel.CrazyPanel();
        Title = new javax.swing.JLabel();
        nameAlternative = new javax.swing.JLabel();
        txnameAlternative = new javax.swing.JTextField();
        btSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        crazyPanel1.setFlatLafStyleComponent(new raven.crazypanel.FlatLafStyleComponent(
            "[light]border:0,0,0,0,shade(@background,5%),,20;[dark]border:0,0,0,0,tint(@background,5%),,20;[light]background:shade(@background,2%);[dark]background:tint(@background,2%)",
            new String[]{
                "font:bold +10",
                "",
                "showClearButton:true",
                ""
            }
        ));
        crazyPanel1.setMigLayoutConstraints(new raven.crazypanel.MigLayoutConstraints(
            "wrap 2,fillx,insets 25",
            "[grow 0,trail]15[fill]",
            "",
            new String[]{
                "wrap,al lead",
                "",
                "",
                "span 2,al trail"
            }
        ));

        Title.setText("Ubah Alternatif");
        crazyPanel1.add(Title);

        nameAlternative.setText("Nama Alternatif");
        crazyPanel1.add(nameAlternative);
        crazyPanel1.add(txnameAlternative);

        btSave.setText("Simpan");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });
        crazyPanel1.add(btSave);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(crazyPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(crazyPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        String newName = txnameAlternative.getText().trim();

        if (newName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama Alternatif tidak boleh kosong.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try (
            Connection conn = Connections.getConnection()
        ) {
            String query = "UPDATE alternatif SET nama_alternatif = ? WHERE kode_alternatif = ?";
            try (PreparedStatement ps = conn.prepareStatement(query)) {
                ps.setString(1, newName);
                ps.setString(2, kodeAlternatif);

                int rowsUpdated = ps.executeUpdate();

                if (rowsUpdated > 0) {
                    JOptionPane.showMessageDialog(this, "Alternatif berhasil diperbarui.");
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal memperbarui alternatif.", "Update Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btSaveActionPerformed

    public static void main(String args[]) {
        FlatRobotoFont.install();
        FlatLaf.registerCustomDefaultsSource("crazypanel");
        UIManager.put("defaultFont", new Font(FlatRobotoFont.FAMILY, Font.PLAIN, 13));
        FlatMacLightLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
            }
        });
    }       
            

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JButton btSave;
    private raven.crazypanel.CrazyPanel crazyPanel1;
    private javax.swing.JLabel nameAlternative;
    private javax.swing.JTextField txnameAlternative;
    // End of variables declaration//GEN-END:variables
}
